"""GitHub CLI operations for AlgoAtlas vault repository."""

import subprocess
from pathlib import Path
from typing import Optional, Tuple


# Label definitions for PRs
LABEL_DEFINITIONS = {
    "easy": {"color": "00ff00", "description": "Easy difficulty problem"},
    "medium": {"color": "ffff00", "description": "Medium difficulty problem"},
    "hard": {"color": "ff0000", "description": "Hard difficulty problem"},
    "new-solution": {"color": "0000ff", "description": "First solution for this problem"},
    "alternative-solution": {
        "color": "800080",
        "description": "Alternative solution for existing problem",
    },
}


def _run_gh_command(
    vault_path: Path,
    args: list[str],
) -> Tuple[bool, str]:
    """Run a GitHub CLI command in the vault directory.

    Args:
        vault_path: Path to vault repository.
        args: gh command arguments (without 'gh' prefix).

    Returns:
        Tuple of (success, output/error message).
    """
    try:
        result = subprocess.run(
            ["gh"] + args,
            cwd=vault_path,
            capture_output=True,
            text=True,
            check=True,
        )
        return True, result.stdout.strip()
    except subprocess.CalledProcessError as e:
        return False, e.stderr.strip() or str(e)
    except FileNotFoundError:
        return False, "GitHub CLI (gh) not found. Install from https://cli.github.com/"


def check_gh_installed() -> bool:
    """Check if GitHub CLI is installed and authenticated.

    Returns:
        True if gh is available and authenticated.
    """
    try:
        result = subprocess.run(
            ["gh", "auth", "status"],
            capture_output=True,
            text=True,
        )
        return result.returncode == 0
    except FileNotFoundError:
        return False


def ensure_labels_exist(vault_path: Path) -> Tuple[bool, str]:
    """Ensure all required labels exist in the vault repository.

    Creates labels if they don't exist. Skips existing labels.

    Args:
        vault_path: Path to vault repository.

    Returns:
        Tuple of (success, message).
    """
    created = []
    skipped = []

    for label_name, props in LABEL_DEFINITIONS.items():
        success, output = _run_gh_command(
            vault_path,
            [
                "label", "create", label_name,
                "--color", props["color"],
                "--description", props["description"],
                "--force",
            ],
        )
        if success:
            if "already exists" in output.lower():
                skipped.append(label_name)
            else:
                created.append(label_name)
        else:
            # Label might already exist (gh returns error for existing labels without --force)
            skipped.append(label_name)

    if created:
        return True, f"Created labels: {', '.join(created)}"
    else:
        return True, "All labels already exist"


def get_pr_labels(difficulty: str, is_new_solution: bool) -> list[str]:
    """Get list of labels to apply to a PR.

    Args:
        difficulty: Problem difficulty (Easy/Medium/Hard).
        is_new_solution: True if this is the first solution for the problem.

    Returns:
        List of label names to apply.
    """
    labels = []

    # Add difficulty label
    difficulty_lower = difficulty.lower()
    if difficulty_lower in LABEL_DEFINITIONS:
        labels.append(difficulty_lower)

    # Add solution type label
    if is_new_solution:
        labels.append("new-solution")
    else:
        labels.append("alternative-solution")

    return labels


def create_pull_request(
    vault_path: Path,
    branch_name: str,
    problem_number: int,
    title: str,
    difficulty: str,
    topics: list[str],
    leetcode_url: str,
    labels: Optional[list[str]] = None,
) -> Tuple[bool, str]:
    """Create a pull request using GitHub CLI.

    Args:
        vault_path: Path to vault repository.
        branch_name: Name of the branch to create PR from.
        problem_number: LeetCode problem number.
        title: Problem title.
        difficulty: Problem difficulty (Easy/Medium/Hard).
        topics: List of problem topics/tags.
        leetcode_url: URL to LeetCode problem.
        labels: Optional list of labels to apply to the PR.

    Returns:
        Tuple of (success, pr_url_or_error_message).
    """
    # Build PR title
    pr_title = f"Add {problem_number}. {title}"

    # Build PR body
    topics_str = ", ".join(topics) if topics else "N/A"
    pr_body = f"""## Problem
- **LeetCode:** [{problem_number}. {title}]({leetcode_url})
- **Difficulty:** {difficulty}
- **Topics:** {topics_str}

---
*Generated by [AlgoAtlas](https://github.com/roarceus/algo-atlas)*"""

    # Build command args
    cmd_args = [
        "pr", "create",
        "--title", pr_title,
        "--body", pr_body,
        "--head", branch_name,
    ]

    # Add labels if provided
    if labels:
        for label in labels:
            cmd_args.extend(["--label", label])

    # Create PR using gh CLI
    success, output = _run_gh_command(vault_path, cmd_args)

    if success:
        # Output contains the PR URL
        return True, output
    else:
        return False, f"Failed to create PR: {output}"
